### PR TITLE
Add links to openSUSE build service

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by kojix2** [comment]
Whoa!
That's an official repository distributed by the GR team.
Where did you find this?

**Comment by kojix2** [comment]
It is written in the official reference! Apparently, I missed it for two years.
Thanks!! @bkmgit

**Review by kojix2 — APPROVED** [review]

**Comment by kojix2** [comment]
Thanks!

**Comment by bkmgit** [comment]
@kojix2 Welcome. Thanks for the quick review.

**Comment by kojix2** [comment]
@bkmgit Excellent. Obviously, `export GRDIR=/usr/gr` is better.

**Comment by bkmgit** [comment]
`export GRDIR=/usr/gr` had not worked before. It seems to work now, maybe I needed to do a restart/open fresh terminal.

**Pull request merged**
